title = "Configuration file"


[backend]
db_file_dir = "./data/"
db_file = "mutual-fund.db"
tables.historical_nav = 'hist_nav_dim' # TODO Check nested keys

[logging]
level = "DEBUG"
file_name = "logs/app.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
date_format = "%Y-%m-%d %H:%M:%S"

[fund_details]

fund1.name = "Parag Parikh Flexi Cap Fund - Direct Plan - Growth"
fund1.alias = "ppfas"
fund1.code = 122639

fund2.name = "Mirae Asset Large Cap Fund - Growth Plan"
fund2.alias = "mirae"
fund2.code = 107578

fund3.name = "UTI Nifty 50 Index Fund - Growth Option- Direct"
fund3.alias = "nifty50"
fund3.code = 120716

fund4.name = "ICICI Prudential Long Term Equity Fund (Tax Saving) - Growth"
fund4.alias = "icici_tax"
fund4.code = 100354

fund5.name = "ICICI Prudential Smallcap Fund - Growth"
fund5.alias = "icici_scap"
fund5.code = 106823

fund6.name = "Franklin India Prima Fund-Growth"
fund6.alias = "prima"
fund6.code = 100473

fund7.name = "Aditya Birla Sun Life Tax Relief '96 - Growth Option"
fund7.alias = "absl96"
fund7.code = 107745

fund8.name = ''
fund8.alias = ''
fund8.code = 0

fund9.name = ''
fund9.alias = ''
fund9.code = 0
